### ISSUE TITLE
Detect empty boxes

### ISSUE THREAD

**Issue by jchoyt** [jchoyt/WoolfPostalService#1]
Know if a shulker box is empty when it's placed by a player.

TODO - what to do if it is?  Don't report it?  Report it if it goes from non-empty to empty?

**Comment by Woolf622** [comment]
Michiganamam2 placed a (**Empty**) package for pickup at dropoff (-33 68 -8 in ASM).  that would be all the information needed i think. That way i know if it's a priority or if its just going back to the WPS

**Comment by jchoyt** [comment]
Check https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Container.html#getInventory()

and https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/Inventory.html getEmpty()
